SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `cookApp` DEFAULT CHARACTER SET utf8mb4 ;
USE `cookApp` ;


CREATE TABLE IF NOT EXISTS `recipes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `dishName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 0001;

CREATE TABLE IF NOT EXISTS `ingredients` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  'recipe_id' BIGINT NOT NULL,
  `ingredient` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY ('recipe_id') REFERENCES recipes(id)
)
ENGINE = InnoDB
AUTO_INCREMENT = 0001;

CREATE TABLE IF NOT EXISTS `recipes_to_ingredients` (
  `recipe_id` BIGINT NOT NULL,
  'ingredient_id' BIGINT NOT NULL,
  `amount` INTEGER NOT NULL,
  'measurement' VARCHAR(10),
  FOREIGN KEY ('recipe_id') REFERENCES recipes(id),
  FOREIGN KEY ('ingredient_id') REFERENCES ingredients(id)
)
ENGINE = InnoDB



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;