SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


CREATE SCHEMA IF NOT EXISTS `bank` DEFAULT CHARACTER SET utf8 ;
USE `bank` ;

CREATE TABLE IF NOT EXISTS `users` (
  `personal_code` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`personal_code`)
)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `bank_accounts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `personal_code` VARCHAR(100) NOT NULL,
  `role` VARCHAR(100) NOT NULL,
  `balance` int,
  PRIMARY KEY (`id`, `personal_code`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1;

ALTER TABLE `bank_accounts`
ADD FOREIGN KEY (`personal_code`) REFERENCES `users`(`personal_code`);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;