SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


CREATE SCHEMA IF NOT EXISTS `java2test` DEFAULT CHARACTER SET utf8 ;
USE `java2test` ;

CREATE TABLE IF NOT EXISTS `accounts` (
`ID` INT NOT NULL auto_increment,
  `Name` VARCHAR(20) NOT NULL,
  `Surname` VARCHAR(30) NULL default "Doe",
  `Balance` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
  )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `transactions` (
`id` INT NOT NULL,
`transactionnumber` INT NOT NULL auto_increment,
`amount` INT NOT NULL,
`time` TIMESTAMP,
  PRIMARY KEY (`transactionnumber`)
  )
ENGINE = InnoDB;
